{% set name = "apache-airflow-providers-mysql" %}
{% set version = "5.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e9255c4ad76d1c37913d556bd554ece538e1687adcdc60da7b635ab796eb44b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow >=2.6.0
    # 8.0.31 has bad dependencies
    - mysql-connector-python >=8.0.11
    - mysqlclient >=1.3.6

test:
  imports:
    - airflow.providers.mysql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-mysql for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/mysql/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-mysql/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
