{% set name = "apache-airflow-providers-mysql" %}
{% set version = "5.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_mysql-{{ version }}.tar.gz
  sha256: c5b5cb92ef21690da87d54677940452ea6fbd26e0a24a9383b43edb01fe0a7e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9,<4.dev0
    - apache-airflow-providers-common-sql >=1.20.0
    - apache-airflow >=2.8.0
    # 8.0.31 has bad dependencies
    - mysql-connector-python >=8.0.29
    - mysqlclient >=1.4.0

test:
  imports:
    - airflow.providers.mysql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-mysql for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/mysql/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-mysql/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
