{% set name = "apache-airflow-providers-mysql" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_mysql-{{ version }}.tar.gz
  sha256: 79c043e6c6888fa5f036f76d16f4e2d62b09b94a022603e07e885d50a2793b79

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.10.1
    - pip
  run:
    - aiomysql >=0.2.0
    - python >={{ python_min }}
    - apache-airflow-providers-common-sql >=1.20.0
    - apache-airflow >=2.9.0
    # 8.0.31 has bad dependencies
    - mysql-connector-python >=8.0.29,!=8.0.31
    - mysqlclient >=1.4.0

test:
  imports:
    - airflow.providers.mysql
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-mysql for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/mysql/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-mysql/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
