context:
  name: apache-airflow-providers-mysql
  version: "6.6.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_mysql-${{ version }}.tar.gz
  sha256: 0eeb2303163e2348e930499779be8a347902d1e2fce894192dac4d810a1336a4

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==4.0.2
  run:
    - python >=${{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.12.0
    - apache-airflow-providers-common-sql >=1.32.0
    - mysqlclient >=2.2.5
    # tightest of upstream's exclusions (python >=3.12)
    - mysql-connector-python >=9.1.0,!=9.7.0
    - aiomysql >=0.2.0
    - pymysql >=1.0.3,<1.2

tests:
  - python:
      imports:
        - airflow.providers.mysql
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-mysql for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-mysql/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
